version: '3.8'
services:

    # Data Product
    osc-dm-product-srv:
        image: ${DOCKERHUB_USERNAME}/${IMAGE_NAME}:latest
        hostname: ${HOSTNAME}
        # container_name: ${HOSTNAME}
        ports:
        # OUTSIDE:INSIDE
        # curl http://localhost:${SERVER_PORT}/data
        - ${PUBLIC_PORT}:${PRIVATE_PORT}
        volumes:
        - ${PROJECT_DIR}/config/${CONFIG_NAME}:/app/config
        - ${DATA_DIR}/dataproducts:/app/dataproducts
        networks:
        - localnet
        environment:
        - OPENAI_API_KEY=${OPENAI_API_KEY}

networks:
    localnet:
        external: true